name: deploy
on:
  - workflow_dispatch
inputs:
  firstName:
    description: 'Your first name'
    required: true
  lastName:
    description: 'Your last name'
    required: true
  yearOfBirth:
    description: 'Birthdate year (at least greater than 1900 ... :D)'
    required: true
  monthOfBirth:
    description: 'Birthdate month (between 1 and 12)'
    required: true
  dayOfBirth:
    description: 'Birthdate day (between 1 and 31)'
    required: true
  cityOfBirth:
    description: 'City you were born'
    required: true
  address:
    description: 'Your current address'
    required: true
  city:
    description: 'Your current city'
    required: true
  postalCode:
    description: 'Your current postal code'
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [cpu, gpu]
        distribution: [3.6, 3.7, 3.8, conda]
        model: [modelless, 2stems, 4stems, 5stems]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      # ----------------------------------------------------------------------
      # Note: base image building and env setup.
      - name: Setup Python distribution
        run: |
          echo "::set-env name=base::python:${{ matrix.distribution }}"
          echo "::set-env name=tag::${{ matrix.distribution }}"
          echo "::set-env name=file::spleeter"
          echo "::set-env name=package::spleeter"